/*
  ==============================================================================

    LayoutFingerprintExportTool.cpp
    Writes WebUI/generated/gp-layout.generated.js: the layout fingerprint the
    page compares the loaded `.wasm` against. Usage:

                   NEURONiK_LayoutExport [outputDirectory]

                 Default output directory is WebUI/generated, resolved relative
                 to the current working directory when the argument is not
                 absolute.

    POR QUE UN TERCER EXPORTADOR y no un numero en el JS. La firma sale de
    `globalParamsLayoutFingerprint()`, en la MISMA cabecera que construye el
    layout que publica el puente. Si la pagina llevara el numero escrito a
    mano, seria una COPIA del struct --justo lo que se ha estado quitando
    toda la sesion-- y se quedaria vieja sin que nada la note: cambiaria el
    struct, el `.wasm` se recompilaria bien, y la pagina compararia contra un
    numero de ayer y direia que el binario esta equivocado cuando lo que
    esta equivocado es el numero. Un generador hace que la copia no exista:
    el valor sale de la tabla, y regenerar es un comando.

    SIN JUCE, igual que `NEURONiK_FxExport`: la cabecera del layout es
    JUCE-free, y un exportador que necesitara JUCE para leer un FNV seria el
    primer sitio donde dejaria de compilar solo.

  ==============================================================================
*/

#include "../Source/Wasm/GlobalParamsLayout.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <string>

namespace
{

bool writeFile (const std::string& path, const std::string& contents, std::string& error)
{
    std::ofstream out (path, std::ios::binary | std::ios::trunc);

    if (! out)
    {
        error = "no se pudo abrir " + path + " para escribir";
        return false;
    }

    out << contents;

    if (! out)
    {
        error = "fallo escribiendo en " + path;
        return false;
    }

    return true;
}

/**
 * El fichero que consume la pagina. Va con la CABECERA que la marca como
 * generada, porque lo es: si alguien lo abre para cambiar el numero a mano,
 * el `// @generated` esta a tres lineas de donde mira.
 */
std::string javaScriptArtifact (std::uint32_t fingerprint, std::size_t fieldCount)
{
    return "// @generated by NEURONiK_LayoutExport - do not edit by hand.\n"
           "// Source of truth: Source/Wasm/GlobalParamsLayout.h (globalParamsLayoutFingerprint()).\n"
           "//\n"
           "// La firma que la pagina compara con la que le da el `.wasm` que carga.\n"
           "// Las dos salen de la MISMA tabla: aqui porque la regenera este\n"
           "// exportador, alla porque la calcula el puente. Por eso el aviso\n"
           "// significa algo: si no cuadran, el binario y la pagina son de\n"
           "// compilaciones distintas.\n"
           "/**\n"
           " * La firma del layout de GlobalParams contra el que se escribio esta pagina.\n"
           " * @type {number}\n"
           " */\n"
           "export const GP_LAYOUT_FINGERPRINT = "
        + std::to_string (fingerprint) + ";\n"
          "\n"
          "/** Cuantos campos del espejo publica el motor de esta compilacion.\n"
          " * @type {number}\n"
          " */\n"
          "export const GP_LAYOUT_FIELD_COUNT = "
        + std::to_string (fieldCount) + ";\n";
}

} // namespace

int main (int argc, char* argv[])
{
    const std::string directory = argc > 1 ? std::string (argv[1])
                                           : std::string ("WebUI/generated");

    const auto fingerprint = globalParamsLayoutFingerprint();
    const auto fieldCount = globalParamsLayout().size();

    std::string error;

    if (! writeFile (directory + "/gp-layout.generated.js",
                     javaScriptArtifact (fingerprint, fieldCount), error))
    {
        std::cerr << "NEURONiK layout export failed: " << error << '\n';
        return 1;
    }

    std::cout << "NEURONiK layout export\n"
              << "  output directory : " << directory << '\n'
              << "  fields           : " << fieldCount << '\n'
              << "  fingerprint      : 0x" << std::hex << fingerprint << std::dec
              << " (" << fingerprint << ")\n"
              << "  file             : gp-layout.generated.js\n";

    return 0;
}
