/*
  ==============================================================================

    ParameterDescriptorExport.cpp

  ==============================================================================
*/

#include "ParameterDescriptorExport.h"

#include <cmath>

namespace NEURONiK::State
{
namespace
{
    constexpr const char* generatedHeader =
        "// @generated by NEURONiK_ParameterExport — do not edit by hand.\n"
        "// Source of truth: Source/State/ParameterDefinitions.h (createParameterLayout).\n";

    /** @brief Deterministic number formatting shared by every artifact. */
    juce::String formatNumber (float value)
    {
        if (std::isfinite (value) && value == std::floor (value) && std::abs (value) < 1.0e7f)
            return juce::String (juce::roundToInt (value));

        juce::String text (value, 7);

        while (text.containsChar ('.') && text.endsWithChar ('0'))
            text = text.dropLastCharacters (1);

        if (text.endsWithChar ('.'))
            text = text.dropLastCharacters (1);

        return text;
    }

    juce::String formatBool (bool value)
    {
        return value ? "true" : "false";
    }

    juce::String quote (const juce::String& text)
    {
        juce::String out;
        out += '"';

        for (const auto character : text)
        {
            switch (character)
            {
                case '"':  out += "\\\""; break;
                case '\\': out += "\\\\"; break;
                case '\n': out += "\\n";  break;
                case '\r': out += "\\r";  break;
                case '\t': out += "\\t";  break;
                default:   out += juce::String::charToString (character); break;
            }
        }

        out += '"';
        return out;
    }

    juce::String formatChoices (const juce::StringArray& choices, const juce::String& separator)
    {
        juce::StringArray quoted;

        for (const auto& choice : choices)
            quoted.add (quote (choice));

        return quoted.joinIntoString (separator);
    }

    /** @brief How many descriptors fall into each DSP status. */
    struct StatusCounts
    {
        int implemented = 0;
        int uiOnly = 0;
        int notRouted = 0;

        int total() const { return implemented + uiOnly + notRouted; }
    };

    StatusCounts countStatuses (const std::vector<ParameterDescriptor>& descriptors)
    {
        StatusCounts counts;

        for (const auto& descriptor : descriptors)
        {
            switch (descriptor.dspStatus)
            {
                case ParameterDspStatus::uiOnly:    ++counts.uiOnly;    break;
                case ParameterDspStatus::notRouted: ++counts.notRouted; break;
                case ParameterDspStatus::implemented:
                default:                            ++counts.implemented; break;
            }
        }

        return counts;
    }
}

juce::String buildParameterArtifactsJson()
{
    const auto descriptors = getParameterDescriptors();
    const auto unrouted = getUnroutedParameterIds();

    juce::String json;
    json << "{\n";
    json << "  \"source\": \"Source/State/ParameterDefinitions.h\",\n";
    json << "  \"parameters\": [\n";

    for (size_t index = 0; index < descriptors.size(); ++index)
    {
        const auto& descriptor = descriptors[index];

        json << "    {\n";
        json << "      \"id\": " << quote (descriptor.id) << ",\n";
        json << "      \"name\": " << quote (descriptor.name) << ",\n";
        json << "      \"group\": " << quote (descriptor.group) << ",\n";
        json << "      \"unit\": " << quote (descriptor.unit) << ",\n";
        json << "      \"kind\": " << quote (parameterKindName (descriptor.kind)) << ",\n";
        json << "      \"minValue\": " << formatNumber (descriptor.minValue) << ",\n";
        json << "      \"maxValue\": " << formatNumber (descriptor.maxValue) << ",\n";
        json << "      \"defaultValue\": " << formatNumber (descriptor.defaultValue) << ",\n";
        json << "      \"defaultNormalized\": " << formatNumber (descriptor.defaultNormalized) << ",\n";
        json << "      \"interval\": " << formatNumber (descriptor.interval) << ",\n";
        json << "      \"skew\": " << formatNumber (descriptor.skew) << ",\n";
        json << "      \"symmetricSkew\": " << formatBool (descriptor.symmetricSkew) << ",\n";
        json << "      \"discrete\": " << formatBool (descriptor.discrete) << ",\n";
        json << "      \"choices\": [" << formatChoices (descriptor.choices, ", ") << "],\n";
        json << "      \"defaultChoiceIndex\": " << descriptor.defaultChoiceIndex << ",\n";
        json << "      \"dspStatus\": " << quote (parameterDspStatusName (descriptor.dspStatus)) << ",\n";
        json << "      \"engines\": " << quote (parameterEngineName (descriptor.engines)) << ",\n";
        json << "      \"dspNote\": " << quote (descriptor.dspNote) << "\n";
        json << "    }" << (index + 1 < descriptors.size() ? "," : "") << "\n";
    }

    const auto counts = countStatuses (descriptors);

    json << "  ],\n";
    json << "  \"unroutedParameterIds\": [" << formatChoices (unrouted, ", ") << "],\n";
    json << "  \"unroutedParameters\": [\n";

    for (int index = 0; index < unrouted.size(); ++index)
    {
        json << "    {\n";
        json << "      \"id\": " << quote (unrouted[index]) << ",\n";
        json << "      \"dspStatus\": \"notInLayout\",\n";
        json << "      \"dspNote\": " << quote (dspNoteForUnroutedId (unrouted[index])) << "\n";
        json << "    }" << (index + 1 < unrouted.size() ? "," : "") << "\n";
    }

    json << "  ],\n";
    json << "  \"summary\": {\n";
    json << "    \"total\": " << counts.total() << ",\n";
    json << "    \"implemented\": " << counts.implemented << ",\n";
    json << "    \"uiOnly\": " << counts.uiOnly << ",\n";
    json << "    \"notRouted\": " << counts.notRouted << ",\n";
    json << "    \"notInLayout\": " << unrouted.size() << "\n";
    json << "  }\n";
    json << "}\n";

    return json;
}

juce::String buildParameterArtifactsJavaScript()
{
    const auto descriptors = getParameterDescriptors();
    const auto unrouted = getUnroutedParameterIds();

    juce::String js;
    js << generatedHeader;
    js << "\n";
    js << "/** @typedef {'float' | 'choice' | 'bool'} ParameterKind */\n";
    js << "\n";
    js << "/** @type {ReadonlyArray<import('./parameters.generated.d.ts').ParameterDescriptor>} */\n";
    js << "export const PARAMETERS = [\n";

    for (const auto& descriptor : descriptors)
    {
        js << "  {\n";
        js << "    id: " << quote (descriptor.id) << ",\n";
        js << "    name: " << quote (descriptor.name) << ",\n";
        js << "    group: " << quote (descriptor.group) << ",\n";
        js << "    unit: " << quote (descriptor.unit) << ",\n";
        js << "    kind: " << quote (parameterKindName (descriptor.kind)) << ",\n";
        js << "    minValue: " << formatNumber (descriptor.minValue) << ",\n";
        js << "    maxValue: " << formatNumber (descriptor.maxValue) << ",\n";
        js << "    defaultValue: " << formatNumber (descriptor.defaultValue) << ",\n";
        js << "    defaultNormalized: " << formatNumber (descriptor.defaultNormalized) << ",\n";
        js << "    interval: " << formatNumber (descriptor.interval) << ",\n";
        js << "    skew: " << formatNumber (descriptor.skew) << ",\n";
        js << "    symmetricSkew: " << formatBool (descriptor.symmetricSkew) << ",\n";
        js << "    discrete: " << formatBool (descriptor.discrete) << ",\n";
        js << "    choices: [" << formatChoices (descriptor.choices, ", ") << "],\n";
        js << "    defaultChoiceIndex: " << descriptor.defaultChoiceIndex << ",\n";
        js << "    dspStatus: " << quote (parameterDspStatusName (descriptor.dspStatus)) << ",\n";
        js << "    engines: " << quote (parameterEngineName (descriptor.engines)) << ",\n";
        js << "    dspNote: " << quote (descriptor.dspNote) << ",\n";
        js << "  },\n";
    }

    const auto counts = countStatuses (descriptors);

    js << "];\n";
    js << "\n";
    js << "/** @type {Readonly<Record<string, import('./parameters.generated.d.ts').ParameterDescriptor>>} */\n";
    js << "export const PARAMETERS_BY_ID = Object.freeze (\n";
    js << "  Object.fromEntries (PARAMETERS.map ((descriptor) => [descriptor.id, descriptor])),\n";
    js << ");\n";
    js << "\n";
    js << "/** IDs declared in the C++ IDs namespace but not routed to the layout yet. */\n";
    js << "export const UNROUTED_PARAMETER_IDS = [" << formatChoices (unrouted, ", ") << "];\n";
    js << "\n";
    js << "/** Same entries with an explanation of why they are not in the layout. */\n";
    js << "export const UNROUTED_PARAMETERS = [\n";

    for (const auto& id : unrouted)
    {
        js << "  { id: " << quote (id) << ", dspStatus: 'notInLayout', dspNote: "
           << quote (dspNoteForUnroutedId (id)) << " },\n";
    }

    js << "];\n";
    js << "\n";
    js << "/** Contract health, so a screen never has to hard code it. */\n";
    js << "export const CONTRACT_SUMMARY = Object.freeze ({\n";
    js << "  total: " << counts.total() << ",\n";
    js << "  implemented: " << counts.implemented << ",\n";
    js << "  uiOnly: " << counts.uiOnly << ",\n";
    js << "  notRouted: " << counts.notRouted << ",\n";
    js << "  notInLayout: " << unrouted.size() << ",\n";
    js << "});\n";

    return js;
}

juce::String buildParameterArtifactsTypeScript()
{
    juce::String ts;
    ts << generatedHeader;
    ts << "\n";
    ts << "export type ParameterKind = 'float' | 'choice' | 'bool';\n";
    ts << "\n";
    ts << "export interface ParameterDescriptor {\n";
    ts << "  readonly id: string;\n";
    ts << "  readonly name: string;\n";
    ts << "  readonly group: string;\n";
    ts << "  readonly unit: string;\n";
    ts << "  readonly kind: ParameterKind;\n";
    ts << "  readonly minValue: number;\n";
    ts << "  readonly maxValue: number;\n";
    ts << "  readonly defaultValue: number;\n";
    ts << "  readonly defaultNormalized: number;\n";
    ts << "  readonly interval: number;\n";
    ts << "  readonly skew: number;\n";
    ts << "  readonly symmetricSkew: boolean;\n";
    ts << "  readonly discrete: boolean;\n";
    ts << "  readonly choices: readonly string[];\n";
    ts << "  readonly defaultChoiceIndex: number;\n";
    ts << "  readonly dspStatus: DspStatus;\n";
    ts << "  readonly engines: EngineCoverage;\n";
    ts << "  readonly dspNote: string;\n";
    ts << "}\n";
    ts << "\n";
    ts << "export type DspStatus = 'implemented' | 'uiOnly' | 'notRouted';\n";
    ts << "export type EngineCoverage = 'both' | 'neuronik' | 'neurotik' | 'none';\n";
    ts << "\n";
    ts << "export interface UnroutedParameter {\n";
    ts << "  readonly id: string;\n";
    ts << "  readonly dspStatus: 'notInLayout';\n";
    ts << "  readonly dspNote: string;\n";
    ts << "}\n";
    ts << "\n";
    ts << "export interface ContractSummary {\n";
    ts << "  readonly total: number;\n";
    ts << "  readonly implemented: number;\n";
    ts << "  readonly uiOnly: number;\n";
    ts << "  readonly notRouted: number;\n";
    ts << "  readonly notInLayout: number;\n";
    ts << "}\n";
    ts << "\n";
    ts << "export declare const PARAMETERS: readonly ParameterDescriptor[];\n";
    ts << "export declare const PARAMETERS_BY_ID: Readonly<Record<string, ParameterDescriptor>>;\n";
    ts << "export declare const UNROUTED_PARAMETER_IDS: readonly string[];\n";
    ts << "export declare const UNROUTED_PARAMETERS: readonly UnroutedParameter[];\n";
    ts << "export declare const CONTRACT_SUMMARY: ContractSummary;\n";

    return ts;
}

ParameterArtifacts buildParameterArtifacts()
{
    ParameterArtifacts artifacts;
    artifacts.json = buildParameterArtifactsJson();
    artifacts.javaScript = buildParameterArtifactsJavaScript();
    artifacts.typeScript = buildParameterArtifactsTypeScript();
    return artifacts;
}

bool writeParameterArtifacts (const juce::File& directory, juce::String& errorMessage)
{
    if (! directory.createDirectory())
    {
        errorMessage = "Cannot create output directory: " + directory.getFullPathName();
        return false;
    }

    const auto artifacts = buildParameterArtifacts();

    const struct
    {
        const char* fileName;
        const juce::String* contents;
    } files[] =
    {
        { ParameterArtifacts::jsonFileName, &artifacts.json },
        { ParameterArtifacts::javaScriptFileName, &artifacts.javaScript },
        { ParameterArtifacts::typeScriptFileName, &artifacts.typeScript }
    };

    for (const auto& file : files)
    {
        const auto target = directory.getChildFile (file.fileName);

        if (! target.replaceWithText (*file.contents, false, false, "\n"))
        {
            errorMessage = "Cannot write file: " + target.getFullPathName();
            return false;
        }
    }

    return true;
}

} // namespace NEURONiK::State
